[BACKPORTING]: max9286: Support v4.14 (KPB version)
Rather than backport 23 patches which pull in the bus type distinctions,
Simply revert back to the old bus type descriptions.

This fixes:

.../linux/drivers/media/i2c/max9286.c:987:24:
error: ‘V4L2_MBUS_CSI2_DPHY’ undeclared (first use in this function);
did you mean ‘V4L2_MBUS_CSI2’?
    if (vep.bus_type != V4L2_MBUS_CSI2_DPHY) {
                        ^~~~~~~~~~~~~~~~~~~
                        V4L2_MBUS_CSI2

Signed-off-by: Kieran Bingham <kieran.bingham@ideasonboard.com>

[WORKAROUND]: max9286: Use old v4l2_fwnode_endpoint_alloc_parse()

the max9286 v5 driver is based on v5.0, where v4l2_fwnode_endpoint_alloc_parse()
stores the results in a structure which is passed by pointer.

In v4.14, this is instead returned as a pointer. Adapt as necessary

Signed-off-by: Kieran Bingham <kieran.bingham@ideasonboard.com>

[WORKAROUND]: max9286: FWNODE Api change

Another minor fixup to the max9826 to account for fwnode api changes.

Signed-off-by: Kieran Bingham <kieran.bingham@ideasonboard.com>

[WORKAROUND]: max9286: Handle async notifier API change

Convert the max9286 to use the old style async notifiers.

Signed-off-by: Kieran Bingham <kieran.bingham@ideasonboard.com>